_BASE_: ../Base-SBS.yml
MODEL:
  META_ARCHITECTURE: ParallelBackbones
  BACKBONES:
    - NAME: build_resnest_backbone
      INPUT_DIM: 2048  # Adjust this according to the output dimension of ResNet backbone
    - NAME: build_vit_backbone
      INPUT_DIM: 768   # Adjust this according to the output dimension of ViT backbone
  CNN_LAYER:
    NAME: ConcatenationCNN  # You can use different fusion strategies here if needed
    INPUT_DIMS: [2048, 768]  # Input dimensions should match the output dimensions of the backbones
    OUTPUT_DIM: 1024  # Dimension of the combined feature vector
    KERNEL_SIZE: 3
    STRIDE: 1
    PADDING: 1
    NUM_LAYERS: 1
    CHANNELS: [512]
    ACTIVATION: relu
  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: Identity
    NECK_FEAT: after
    CLS_LAYER: Linear
    NUM_CLASSES: 1000  # Adjust this according to your dataset
  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0. # no smooth
      SCALE: 1.
    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.
  # Other configurations remain unchanged...
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  REA:
    ENABLED: True
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: False
  OPT: SGD
  MAX_EPOCH: 120
  BASE_LR: 0.008
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 64

  SCHED: CosineAnnealingLR
  ETA_MIN_LR: 0.000016

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000

  CLIP_GRADIENTS:
    ENABLED: True

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/sbs_vit_base_VR

